// Generates src/app/routes.tsx from scripts/routes.manifest.json and creates
// placeholder pages for any page file that doesn't exist yet. Run: node scripts/gen-routes.mjs
import fs from "node:fs";
import path from "node:path";
const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), "..");
const rows = JSON.parse(fs.readFileSync(path.join(root, "scripts/routes.manifest.json"), "utf8"));
const shells = { public: "PublicShell", auth: "AuthShell", wizard: "WizardShell", fan: "FanShell", creator: "CreatorShell", admin: "AdminShell", bare: null };
const groups = {};
let created = 0;
for (const [shell, route, page, flag, source] of rows) {
  const file = path.join(root, "src/pages", page + ".tsx");
  if (!fs.existsSync(file)) {
    fs.mkdirSync(path.dirname(file), { recursive: true });
    const name = page.split("/").pop();
    fs.writeFileSync(file, `import { PagePlaceholder } from "@/components/PagePlaceholder";\n\n/** Source: ${source} */\nexport default function ${name}() {\n  return <PagePlaceholder title="${name.replace(/([a-z])([A-Z])/g, "$1 $2")}" route="${route}" source={${JSON.stringify(source)}} />;\n}\n`);
    created++;
  }
  (groups[shell] ??= []).push({ route, page, flag });
}
const lazy = (p) => `lazy(() => import("@/pages/${p}"))`;
let out = `// AUTO-GENERATED by scripts/gen-routes.mjs from scripts/routes.manifest.json — edit the manifest, not this file.\nimport { lazy, Suspense, type ReactNode } from "react";\nimport { createBrowserRouter, Navigate } from "react-router";\nimport { PublicShell, AuthShell, WizardShell, FanShell, CreatorShell, AdminShell } from "@/layouts/shells";\nimport { FeatureRoute } from "@/components/brand";\nimport { RouteFallback, NotFound } from "@/components/PagePlaceholder";\n\n`;
const ids = new Map();
rows.forEach(([, , page], i) => { if (!ids.has(page)) { ids.set(page, `P${ids.size}`); out += `const ${ids.get(page)} = ${lazy(page)};\n`; } });
out += `\nconst S = (n: ReactNode) => <Suspense fallback={<RouteFallback />}>{n}</Suspense>;\n\nexport const router = createBrowserRouter([\n`;
for (const [shell, list] of Object.entries(groups)) {
  const children = list.map(({ route, page, flag }) => {
    const el = flag ? `<FeatureRoute flag="${flag}"><${ids.get(page)} /></FeatureRoute>` : `<${ids.get(page)} />`;
    return `      { path: "${route}", element: S(${el}) },`;
  }).join("\n");
  if (shells[shell]) out += `  {\n    element: <${shells[shell]} />,\n    children: [\n${children}\n    ],\n  },\n`;
  else out += children.replace(/^      /gm, "  ") + "\n";
}
out += `  { path: "/dashboard", element: <Navigate to="/home" replace /> },\n  { element: <PublicShell />, children: [{ path: "*", element: <NotFound /> }] },\n]);\n`;
fs.mkdirSync(path.join(root, "src/app"), { recursive: true });
fs.writeFileSync(path.join(root, "src/app/routes.tsx"), out);
console.log(`routes: ${rows.length}, placeholders created: ${created}`);
